language: shell # (unofficial)
distro: trusty
sudo: false

env:
  # outdated/legacy
  - TEST_SHELL=sh BORG=1.0.2 BORG_SOURCE=binary BORG_VARIANT=borg-linux64 # old, Ubuntu Xenial
  # old stable
  # - TEST_SHELL=sh BORG=stable BORG_VARIANT=borg-linux64 BORG_SOURCE=binary # stable, unsupported by current TravisCi config
  - TEST_SHELL=zsh BORG=1.0.11 BORG_SOURCE=binary BORG_VARIANT=borg-linux64 # up-to-date/stable (most distros)
  - TEST_SHELL=bash BORG=1.0.11 BORG_SOURCE=binary BORG_VARIANT=borg-linux64 # up-to-date/stable (most distros)
  # new stable
  - TEST_SHELL=sh BORG=1.1.0 BORG_SOURCE=binary BORG_VARIANT=borg-linux64 # up-to-date/stable (upstream)
  # - TEST_SHELL=sh BORG=nightly # dev version, unsupported by current TravisCi config
before_script:
  # add custom binary path
  - mkdir "$PWD/custombin/"
  - export PATH="$PWD/custombin/:$PATH"
  # installing borg
  - tests/helper/installBorg.sh
  # install shunit2
  - cd tests&&git clone https://github.com/kward/shunit2
  - cd shunit2&&git checkout 697249da081473c1904d84e9aa2dd4633a3115fb
  - cd ../..
  - export SHUNIT_COLOR='always'

script:
  - tests/helper/verifySignature.sh
  - $TEST_SHELL tests/helper/helperCheckVersion.sh
  - tests/testShellcheck.sh
  - tests/unitTests/borgcronStarter.sh
  - tests/unitTests/borgcron.sh
  - tests/unitTests/borgcronReal.sh
  - tests/unitTests/checkLastBackup.sh

addons:
  apt:
    packages:
    - shellcheck
    # shells to check
    - zsh

matrix:
  allow_failures:
  - env: BORG=nightly

notifications:
  email:
    on_success: change
    on_failure: change
